spring:
  application:
    name: "wall-api"
server:
  port: 8888
  servlet:
    context-path: "/wall-api"

wall:
  gitlab:
    branch: >
      <REPLACE BY LIST OF GITLAB BRANCH NAMES SEPARATE BY COMA (,) and BREAK LINE>
       <SAMPLE:
       develop,
       main,...
       >
    ids: >
      <REPLACE BY LIST OF GITLAB PROJECT IDs SEPARATE BY COMA (,) and BREAK LINE>
      <SAMPLE:
      1,
      2,...
      >
    token: "<REPLACE BY PRIVATE ACCESS TOKEN>"
    baseHost: "<REPLACE_BY_GITLAB_BASE_HOST>"
    path: "<REPLACE_BY_GITLAB_PATH_PROJECT>"
